# Generated by Django 5.2.3 on 2025-07-15 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_rename_rating_product_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('idpurchase', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('idsell', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('old_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('old_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sells',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('idrating', models.AutoField(primary_key=True, serialize=False)),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('fk_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.sells')),
            ],
        ),
    ]
