# Generated by Django 5.2.3 on 2025-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msgs',
            fields=[
                ('idmsgs', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=150)),
                ('sender', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Msgs',
                'verbose_name_plural': 'Msgs',
                'ordering': ['idmsgs'],
            },
        ),
    ]
