# Generated by Django 5.2.3 on 2025-06-15 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'Category',
                'ordering': ['idcategory'],
            },
        ),
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('idcms', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField(max_length=10)),
            ],
            options={
                'verbose_name': 'cms',
                'verbose_name_plural': 'Cms',
                'db_table': 'Cms',
                'ordering': ['idcms'],
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('idcolour', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'colour',
                'verbose_name_plural': 'Colours',
                'db_table': 'Colour',
                'ordering': ['idcolour'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=50)),
                ('availability', models.IntegerField()),
                ('size', models.CharField(max_length=4, null=True)),
                ('rating', models.IntegerField()),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('cms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.cms')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.colour')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'Product',
                'ordering': ['idproduct'],
            },
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='media/')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'imagesproduct',
                'verbose_name_plural': 'imagesproduct',
                'db_table': 'imagesproduct',
                'ordering': ['id_product'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('idsubcategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'db_table': 'Subcategory',
                'ordering': ['idsubcategory'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
