# Generated by Django 5.2.3 on 2025-07-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_mainphoto_alter_product_cathegory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.colour'),
        ),
    ]
