# Generated by Django 5.2.3 on 2025-07-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cathegory',
        ),
    ]
