# Generated by Django 5.2.3 on 2025-07-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_cathegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='imagesproduct',
            name='id_imgProduct',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
