# Generated by Django 5.2.3 on 2025-07-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_imagesproduct_id_imagesproduct_id_imgproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='score',
        ),
    ]
