# Generated by Django 5.2.3 on 2025-07-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
